### ISSUE TITLE
replace "endianess" with "byteorder" in SegyAbstractHeader

### ISSUE THREAD

**Issue by anthonytorlucci** [anthonytorlucci/segytools#12]
"byteorder" makes more sense. "endianess" is a made up word!

**Comment by karthikmurali60** [comment]
@anthonytorlucci can I work on this ?

**Comment by anthonytorlucci** [comment]
> @anthonytorlucci can I work on this ?

Thank you for taking an interest @karthikmurali60, but I'm not quite ready to take on contributors. I will begin working on a contributor guide soon.

**Comment by anthonytorlucci** [comment]
completed version 0.2.1
